### ISSUE TITLE
not available for R 3.4.4

### ISSUE THREAD

**Issue by carzamora** [etiennebr/visualraster#15]
hi, can you update your package for R 3.4? 

Warning in install.packages :
  package ‘visualraster’ is not available (for R version 3.4.4)

thanks!!

**Comment by etiennebr** [comment]
Sorry, I missed your issue! `visualraster` isn't on CRAN. The easiest way to install it is with:
``` r
library("devtools")
install_github("etiennebr/visualraster")
``` 
However I can see that the instructions call for a download section (and use `install.packages`), which can be confusing. I'll fix that, thanks.

**Comment by carzamora** [comment]
Ok, the problem is that in CRAN exist another package with that name!
