### ISSUE TITLE
Tiny titles mistakes!

### ISSUE THREAD

**Issue by icarda** [etiennebr/visualraster#9]
First of all I would like you Racine for this close to perfect job, fantastic I really appreciate it. I would like to refer to two small mistakes in your sections titles:

1. rasterToPoints then rasterToPolygons (you have rasterToPoints title for both examples)
2. it is hillShade not hilshade (i.e. double l and S capital)

**Comment by etiennebr** [comment]
Good catch @icarda ! Thanks for contributing. I'm surprised hillShade didn't raise an error on package check, or maybe I overlooked it. I've created a pr, but I'm unable to test it right now, will do as soon as I have a dev environment.

**Comment by icarda** [comment]
It does not because the mistake in the title not in the function call itself :o)
